pipeline {
    agent any

    environment {
        // AWS ECR registry URL
        ECR_REGISTRY = "123456789012.dkr.ecr.us-east-1.amazonaws.com"
        // ECR repository name
        ECR_REPOSITORY = "my-ecr-repo"
        // Docker image tag
        IMAGE_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                     git branch: 'main', url: 'https://github.com/santoshbd67/ThreeTierAppChallenge.git'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ."
                }
            }
        }

        stage('Login to ECR') {
            steps {
                script {
                    sh "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY"
                }
            }
        }

        stage('Push Docker Image to ECR') {
            steps {
                script {
                    sh "docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
                }
            }
        }
    }
}
