pipeline {
    agent any
   
    stages {
        stage('git checkout') {
            steps {
               git branch: 'main', url: 'https://github.com/santoshbd67/ThreeTierAppChallenge.git'
            }
        }
        
        stage('build and push docker images') {
            steps {
               script{
                   withDockerRegistry(credentialsId: 'dockerhub') {
                       sh "docker build -t backend -f backend/Dockerfile ."
                       sh "docker tag backend santoshbd67/backend:latest"
                       sh "docker push santoshbd67/backend:latest"
                 }
               }
            }
        }
    }
}
