pipeline {
    agent any
   
    environment{
        SCANNER_HOME=tool 'sonar-scanner'
        
    }

    stages {
        stage('git checkout') {
            steps {
                git changelog: false, poll: false, url: 'https://github.com/santoshbd67/ThreeTierAppChallenge.git'
            }
        }
        
        stage('build and push docker images') {
            steps {
               script{
                   withDockerRegistry(credentialsId: 'dockerhub') {
                       sh "docker build -t backend ."
                       sh "docker tag backend santoshbd67/backend:latest"
                       sh "docker push santoshbd67/backend:latest"
                 }
               }
            }
        }
    }
}
